# Generated by Django 5.2.16 on 2026-08-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('maintenance_mode_enabled', models.BooleanField(default=False, verbose_name='Wartungsmodus aktiviert')),
                ('maintenance_title', models.CharField(default='Wir sind bald wieder für Sie da.', max_length=200, verbose_name='Überschrift der Wartungsseite')),
                ('maintenance_message', models.TextField(default='Unsere Website wird derzeit gewartet. Bitte versuchen Sie es später erneut.', verbose_name='Text der Wartungsseite')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert')),
            ],
            options={
                'verbose_name': 'Website-Konfiguration',
                'verbose_name_plural': 'Website-Konfiguration',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='core_site_configuration_singleton')],
            },
        ),
    ]
